### ISSUE TITLE
CMake fails trying to download glslang

### ISSUE THREAD

**Issue by Hay1tsme** [EQMG/Acid#105]
CMake attempts to download https://github.com/KhronosGroup/glslang/archive/10-11.0.0.tar.gz, which 404s and causes the generation to fail. This can by bypassed by setting the FETCHCONTENT_SOURCE_DIR_GLSLANG variable, though.

**Comment by mattparks** [comment]
https://github.com/EQMG/Acid/commit/8bfeb86535dfd69f81567ffcbbe3514fb6b34aa0 should fix the deleted glslang Git release on develop.

**Comment by Hay1tsme** [comment]
can confirm it works without issue, thanks!
