### ISSUE TITLE
This application has requested the Runtime to terminate it in an unusual way

### ISSUE THREAD

**Issue by EpicSpaces** [EQMG/Acid#109]
:/ what should I do, I've builded the editor, I got this error This application has requested the Runtime to terminate it in an unusual way, and can we migrate to opengl/freeglut ? I hate vulkan it's heavy

**Comment by mattparks** [comment]
The editor is very broken and still a WIP, the examples+tutorials should run fine. This engine is a Vulkan engine, you can look at other great OpenGL game engines if that's the graphics API you want to use.
