### ISSUE TITLE
Can`t download the volk package

### ISSUE THREAD

**Issue by ActiveXSturcture** [EQMG/Acid#111]
I use the MSVC and cmake to generate the project ,but when download the needed libraries it crashed.Maybe the Internet issus cause this,but when i check the repository of volk and the makefile URL,I can`t even download that from the web browser.I think maybe the URL is out-of-date!!

**Comment by mattparks** [comment]
What error are you getting exactly? VS should be giving an error output if CMake generation fails.

**Comment by ActiveXSturcture** [comment]
when generate the cmake project,it came out this:
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find OPENALSOFT (missing: OPENALSOFT_LIBRARY OPENALSOFT_INCLUDE_DIR)
-- Found OpenAL: C:/Program Files/openal-soft-1.21.1-bin/libs/Win64/OpenAL32.lib
-- Using Win32 for window creation
-- Using Debug VC++ CRT: MDd
-- Using Release VC++ CRT: MD
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
-- Found PythonInterp: C:/Users/18044/AppData/Local/Programs/Python/Python38/python.exe (found suitable version "3.8.8", minimum required is "3")
CMake Deprecation Warning at build/_deps/bullet3-src/CMakeLists.txt:1 (cmake_minimum_required):

I have the OPENAL-soft in environment path,but it seems doesn`t work.
I download openal-soft from github,and put it int the environment path,did i need another OpenAl SDK from the web and install it?Could it be the reason of this?what exactly openal is and how to install it?

**Comment by mattparks** [comment]
Acid found OpenAL, it will not need OpenAlSoft.

**Comment by ActiveXSturcture** [comment]
Ok, I will give a try ,Thanks
