### ISSUE TITLE
No examples would work

### ISSUE THREAD

**Issue by niansa** [EQMG/Acid#118]
**Describe the bug**
No examples would work. Just a grey screen and double free when closing the window.

**To Reproduce**
1. Compile and build (`-DCMAKE_BUILD_TYPE=Debug -DACID_INSTALL_RESOURCES=ON`)
2. Run something like ./bin/TestFont

**Expected behaviour**
The example should start

**Screenshots**

    Version: 0.14.2
    Git: 1cd00093 on master
    Compiled on: Linux-5.13.8-1-default from: Unix Makefiles with: /usr/bin/c++
    
    [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
    [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
    Audio Device: OpenAL Soft
    Selected Audio Device: "OpenAL Soft"
    Instance Layers: 
    
    Vulkan validation layer not found: "VK_LAYER_KHRONOS_validation"
    Validation layers requested, but not available!
    Discrete Physical Device: 26591 "AMD" "AMD RADV POLARIS10 (ACO)"
    API Version: 1.2.168
    Extensions: VK_KHR_8bit_storage, VK_KHR_16bit_storage, VK_KHR_bind_memory2, VK_KHR_buffer_device_address, VK_KHR_copy_commands2, VK_KHR_create_renderpass2, VK_KHR_dedicated_allocation, VK_KHR_deferred_host_operations, VK_KHR_depth_stencil_resolve, VK_KHR_descriptor_update_template, VK_KHR_device_group, VK_KHR_draw_indirect_count, VK_KHR_driver_properties, VK_KHR_external_fence, VK_KHR_external_fence_fd, VK_KHR_external_memory, VK_KHR_external_memory_fd, VK_KHR_external_semaphore, VK_KHR_external_semaphore_fd, VK_KHR_get_memory_requirements2, VK_KHR_image_format_list, VK_KHR_imageless_framebuffer, VK_KHR_incremental_present, VK_KHR_maintenance1, VK_KHR_maintenance2, VK_KHR_maintenance3, VK_KHR_multiview, VK_KHR_pipeline_executable_properties, VK_KHR_push_descriptor, VK_KHR_relaxed_block_layout, VK_KHR_sampler_mirror_clamp_to_edge, VK_KHR_sampler_ycbcr_conversion, VK_KHR_separate_depth_stencil_layouts, VK_KHR_shader_atomic_int64, VK_KHR_shader_clock, VK_KHR_shader_draw_parameters, VK_KHR_shader_float16_int8, VK_KHR_shader_float_controls, VK_KHR_shader_non_semantic_info, VK_KHR_shader_subgroup_extended_types, VK_KHR_shader_terminate_invocation, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_swapchain, VK_KHR_swapchain_mutable_format, VK_KHR_timeline_semaphore, VK_KHR_uniform_buffer_standard_layout, VK_KHR_variable_pointers, VK_KHR_vulkan_memory_model, VK_KHR_workgroup_memory_explicit_layout, VK_KHR_zero_initialize_workgroup_memory, VK_EXT_4444_formats, VK_EXT_buffer_device_address, VK_EXT_calibrated_timestamps, VK_EXT_conditional_rendering, VK_EXT_custom_border_color, VK_EXT_depth_clip_enable, VK_EXT_depth_range_unrestricted, VK_EXT_descriptor_indexing, VK_EXT_discard_rectangles, VK_EXT_display_control, VK_EXT_extended_dynamic_state, VK_EXT_external_memory_dma_buf, VK_EXT_external_memory_host, VK_EXT_global_priority, VK_EXT_host_query_reset, VK_EXT_image_robustness, VK_EXT_index_type_uint8, VK_EXT_inline_uniform_block, VK_EXT_line_rasterization, VK_EXT_memory_budget, VK_EXT_memory_priority, VK_EXT_pci_bus_info, VK_EXT_pipeline_creation_cache_control, VK_EXT_pipeline_creation_feedback, VK_EXT_private_data, VK_EXT_queue_family_foreign, VK_EXT_robustness2, VK_EXT_sample_locations, VK_EXT_sampler_filter_minmax, VK_EXT_scalar_block_layout, VK_EXT_shader_atomic_float, VK_EXT_shader_demote_to_helper_invocation, VK_EXT_shader_image_atomic_int64, VK_EXT_shader_stencil_export, VK_EXT_shader_subgroup_ballot, VK_EXT_shader_subgroup_vote, VK_EXT_shader_viewport_index_layer, VK_EXT_subgroup_size_control, VK_EXT_texel_buffer_alignment, VK_EXT_transform_feedback, VK_EXT_vertex_attribute_divisor, VK_EXT_ycbcr_image_arrays, VK_AMD_buffer_marker, VK_AMD_device_coherent_memory, VK_AMD_draw_indirect_count, VK_AMD_gcn_shader, VK_AMD_memory_overallocation_behavior, VK_AMD_mixed_attachment_samples, VK_AMD_rasterization_order, VK_AMD_shader_ballot, VK_AMD_shader_core_properties, VK_AMD_shader_core_properties2, VK_AMD_shader_explicit_vertex_parameter, VK_AMD_shader_fragment_mask, VK_AMD_shader_image_load_store_lod, VK_AMD_shader_info, VK_AMD_shader_trinary_minmax, VK_AMD_texture_gather_bias_lod, VK_GOOGLE_decorate_string, VK_GOOGLE_hlsl_functionality1, VK_GOOGLE_user_type, VK_NV_compute_shader_derivatives, VK_VALVE_mutable_descriptor_type, 
    
    Selected Physical Device: 26591 "AMD RADV POLARIS10 (ACO)"
    Working Directory: "/mnt/ghdd/Programme/OSS/Acid/build"
    Failed to mount path Resources/Engine, not found
    File "InputSchemes/DefaultFont.json" loaded in 0.317ms
    File "InputSchemes/DefaultFont.json" saved in 0.111ms
    Font Type "Fonts/ProximaNova-Regular.ttf" loaded 98 glyphs in 248.142ms
    Render Stage created in 0.548ms
    Pipeline Graphics "Shaders/Guis/Gui.frag" loaded in 298.069ms
    Pipeline Graphics "Shaders/Fonts/Font.frag" loaded in 12.516ms

Whereas with all Tutorial executables except 7 (which actually starts but then freezes as in no control possible) I get:

    Version: 0.14.2
    Git: 1cd00093 on master
    Compiled on: Linux-5.13.8-1-default from: Unix Makefiles with: /usr/bin/c++
    
    [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
    [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
    Audio Device: OpenAL Soft
    Selected Audio Device: "OpenAL Soft"
    fish: Job 1, './bin/Tutorial6' terminated by signal SIGSEGV (Address boundary erro

**Hardware:**
 - Device: AMD RX 580
 - OS: OpenSuse Tumbleweed

**Additional context**
I am not doing an in-soure build. The build folder is inside the source root tho:

    mkdir build
    cd build
    cmake .. # options and stuff
    make -j$(nproc)

**Comment by niansa** [comment]
Unit tests fail too:

    [==========] Running 2 tests from 2 test suites.
    [----------] Global test environment set-up.
    [----------] 1 test from RingBuffer
    [ RUN      ] RingBuffer.pushPopResize
    [       OK ] RingBuffer.pushPopResize (0 ms)
    [----------] 1 test from RingBuffer (0 ms total)
    
    [----------] 1 test from Vector2
    [ RUN      ] Vector2.operators
    /build/Acid/Tests/Units/Test_Vector2.cpp:13: Failure
    Expected equality of these values:
      a - b
        Which is: 4.74, -22.6
      acid::Vector2f(4.74, -22.6)
        Which is: 4.74, -22.6
    [  FAILED  ] Vector2.operators (0 ms)
    [----------] 1 test from Vector2 (0 ms total)
    
    [----------] Global test environment tear-down
    [==========] 2 tests from 2 test suites ran. (0 ms total)
    [  PASSED  ] 1 test.
    [  FAILED  ] 1 test, listed below:
    [  FAILED  ] Vector2.operators
    
     1 FAILED TEST

**Comment by alundb** [comment]
You could try replacing "VK_LAYER_KHRONOS_validation"  with "VK_LAYER_LUNARG_standard_validation" and see if that validation layer is found. What version of the vulkan sdk are you running?

**Comment by mattparks** [comment]
You will need to modify the engine code.
Validation layers are defined here: https://github.com/EQMG/Acid/blob/master/Sources/Devices/Instance.cpp#L14
Device extensions are defined here: https://github.com/EQMG/Acid/blob/master/Sources/Devices/LogicalDevice.cpp#L9

**Comment by niansa** [comment]
Nope. That changed absolutely nothing. :-(

**Comment by npfitzenmaier** [comment]
> Unit tests fail too:
> 
> ```
> [==========] Running 2 tests from 2 test suites.
> [----------] Global test environment set-up.
> [----------] 1 test from RingBuffer
> [ RUN      ] RingBuffer.pushPopResize
> [       OK ] RingBuffer.pushPopResize (0 ms)
> [----------] 1 test from RingBuffer (0 ms total)
> 
> [----------] 1 test from Vector2
> [ RUN      ] Vector2.operators
> /build/Acid/Tests/Units/Test_Vector2.cpp:13: Failure
> Expected equality of these values:
>   a - b
>     Which is: 4.74, -22.6
>   acid::Vector2f(4.74, -22.6)
>     Which is: 4.74, -22.6
> [  FAILED  ] Vector2.operators (0 ms)
> [----------] 1 test from Vector2 (0 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 2 tests from 2 test suites ran. (0 ms total)
> [  PASSED  ] 1 test.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] Vector2.operators
> 
>  1 FAILED TEST
> ```

I get the same output. The TestPhysics example is working, but no Font, no overlayDebug and no particles are displayed.
The TestGUI only shows the logo for example and I think it should also show the overlayDebug and some Text.
I'll try to modify the engine code as mattparks mentioned.

System:
AMD Ryzen 9 3900X
GeForce RTX 2070
Windows 11 Pro
Microsoft Visual Studio Community 2022

**Comment by alundb** [comment]
Similar results as above. TestPhysics seems to work great. Tutorial 1 through 6 returns segmentation fault, but Tutorial 7 runs and displays the house model. 

Regarding the failing unit tests, it's an expected behavior when working with equality comparison involving floats. Replacing ASSERT_EQ with ASSERT_FLOAT_EQ and performing the comparison component wise is a simple solution to at least make it pass. 
```
ASSERT_FLOAT_EQ((a - b).x, acid::Vector2f(4.74, -22.6).x);
ASSERT_FLOAT_EQ((a - b).y, acid::Vector2f(4.74, -22.6).y);

```

Would gladly help to investigate some of the issues mentioned here, but not entirely sure where to start. (I hoped the validation layers would point to some issues, but they seem to be happy(?))

**Comment by niansa** [comment]
Moved on to OpenMandriva, but thanks for your help. It seems to work here now.
