### ISSUE TITLE
Enough of this

### ISSUE THREAD

**Issue by ghost** [EQMG/Acid#127]
@mattparks Matt, you are not an engineer (and will never be close). It's a big lie and disrespectful to real engineers (mechanical engineers) for software devs to claim to be "engineers". Software devs will never be close to understand what engineering means or entails. Engineering is a real subject. Engineering involves designing and manufacturing of real-life systems, like turbines, buildings, and mechanical systems, thermofluid systems, etc. Engineering is not about some kids sitting behind a keyboard and writing code. So many software devs are big dumb losers.

**Comment by jellykells** [comment]
account deleted 😂😂😂

**Comment by Kobbersvard** [comment]
Wow, that was something 😲🫣
