### ISSUE TITLE
Build error on Ubuntu22.04

### ISSUE THREAD

**Issue by xwang186** [EQMG/Acid#128]
Env: Ubuntu 22.04, cmake version: 3.22
build step:
1. sudo apt-get install -y build-essential pkg-config g++-10 xorg-dev libglu1-mesa-dev libopenal-dev libvulkan-dev
2. mkdir build
3. cd build
4. cmake ..
5. make -j16

Error msg:

> In file included from /home/xxx/repo/Acid/Sources/Engine/App.hpp:3,
>                  from /home/xxx/repo/Acid/Sources/Engine/Engine.hpp:10,
>                  from /home/xxx/repo/Acid/Sources/Files/Files.hpp:3,
>                  from /home/xxx/repo/Acid/Sources/Bitmaps/Bitmap.cpp:7:
> /home/xxx/repo/Acid/Sources/../External/rocket/rocket.hpp:2086:30: error: no match for ‘operator!=’ (operand types are ‘const std::thread::id’ and ‘std::thread::id’)
>  2086 |                 && thread_id != std::this_thread::get_id();
>       |                    ~~~~~~~~~ ^~ ~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                    |                                    |
>       |                    const std::thread::id                std::thread::id
> /home/xxx/repo/Acid/Sources/../External/rocket/rocket.hpp:1085:17: note: candidate: ‘template<class T, class U> bool rocket::operator!=(const rocket::intrusive_ptr<T>&, const rocket::intrusive_ptr<U>&)’
>  1085 |     inline bool operator != (intrusive_ptr<T> const& a, i

Cmake info:

> -- The CXX compiler identification is GNU 11.2.0
> -- The C compiler identification is GNU 11.2.0
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
> -- Found Threads: TRUE  
>  Vulkan as target
> -- Found OpenALSoft: /usr/lib/x86_64-linux-gnu/libopenal.so  
> -- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
> -- Including X11 support
> -- Found X11: /usr/include   
> -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
> -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
> -- Looking for gethostbyname
> -- Looking for gethostbyname - found
> -- Looking for connect
> -- Looking for connect - found
> -- Looking for remove
> -- Looking for remove - found
> -- Looking for shmat
> -- Looking for shmat - found
> -- Looking for IceConnectionNumber in ICE
> -- Looking for IceConnectionNumber in ICE - found
> -- No build type selected, default to Debug
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.4", minimum required is "3") 
> CMake Deprecation Warning at External/bullet3/CMakeLists.txt:1 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> CMake Warning (dev) at External/bullet3/CMakeLists.txt:7 (PROJECT):
>   Policy CMP0048 is not set: project() command manages VERSION variables.
>   Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   The following variable(s) would be set to empty:
> 
>     PROJECT_VERSION
>     PROJECT_VERSION_MAJOR
>     PROJECT_VERSION_MINOR
>     PROJECT_VERSION_PATCH
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> Linux
> CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindOpenGL.cmake:315 (message):
>   Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
>   available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.
> 
>   FindOpenGL found both a legacy GL library:
> 
>     OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
> 
>   and GLVND libraries for OpenGL and GLX:
> 
>     OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
>     OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
> 
>   OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
>   compatibility with CMake 3.10 and below the legacy GL library will be used.
> Call Stack (most recent call first):
>   External/bullet3/CMakeLists.txt:312 (FIND_PACKAGE)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
> OPENGL FOUND
> /usr/lib/x86_64-linux-gnu/libGL.so/usr/lib/x86_64-linux-gnu/libGLU.so
> CMake Warning (dev) at External/physfs/CMakeLists.txt:14 (project):
>   Policy CMP0048 is not set: project() command manages VERSION variables.
>   Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   The following variable(s) would be set to empty:
> 
>     PROJECT_VERSION
>     PROJECT_VERSION_MAJOR
>     PROJECT_VERSION_MINOR
>     PROJECT_VERSION_PATCH
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- PhysicsFS will build with the following options:
> --   ZIP support: enabled
> --   7zip support: enabled
> --   GRP support: enabled
> --   WAD support: enabled
> --   HOG support: enabled
> --   MVL support: enabled
> --   QPAK support: enabled
> --   SLB support: enabled
> --   VDF support: enabled
> --   ISO9660 support: enabled
> --   Build static library: disabled
> --   Build shared library: enabled
> --   Build stdio test program: disabled
> --   Build Doxygen documentation: disabled
> -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
> -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Failed
> -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
> -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Failed
> -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
> -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
> -- Found Python: /usr/bin/python3.10 (found version "3.10.4") found components: Interpreter 
> -- Configuring done
> -- Generating done

Could anyone fix it? Thanks in advance!

**Comment by mattparks** [comment]
Does this change fix your build?
https://github.com/EQMG/Acid/commit/2ff8adee30cfb571d27a1d937689608ccea12734

**Comment by xwang186** [comment]
> Does this change fix your build? [2ff8ade](https://github.com/EQMG/Acid/commit/2ff8adee30cfb571d27a1d937689608ccea12734)

Nice fix! This definately solves my issue. Now I can build it 100%. Closing this issue accordingly.

**Comment by xwang186** [comment]
@mattparks  BTW, may I ask about if I have the same config as you do? I believe I am seeing similar issue during the execution as well, and it seems to be some different cpp version issue.. (Probably some bugs in CMake file)

**Comment by xwang186** [comment]
@mattparks For example
![image](https://user-images.githubusercontent.com/39249169/179679715-0ced5740-6a3c-4fdb-9621-25484921ee29.png)

I don't want to open new issues for you, because it seems to be some missing in the environments.
Your CI "ctest" doesn't have any issue; but all executables I have different issues.

**Comment by mattparks** [comment]
Was that just Editor crashing during runtime? I haven't tested it in a while so the new multi-window code might be broken with it.
I currently don't have a Linux install with graphics, I'm trying to update the GCC CI and modularize builds on [develop/modularize](https://github.com/EQMG/Acid/tree/develop/modularize) so I probably need to get a physical machine running soon.

**Comment by xwang186** [comment]
@mattparks No worries lol. If it is working on windows, like before the change of "thread" change under this ticket, I think it is most likely some cmake issue, e.x. the cmake doesn't select stdc++17. You can see that this crash is from a vector usage. So I guess the compiler version is slightly different.

Could you pls give me a try, clean the build on a windows machine and try to build it under commandline, use
cmake ..
cmake --build .
and see if you have the same issue? I see that someone has crash under cmake but no issue using visual studio, so I am guessing VS is overwriting some settings. Should be some minor fix I believe
