### ISSUE TITLE
Packaging on Linux is rough

### ISSUE THREAD

**Issue by sum01** [EQMG/Acid#24]
I was attempting to package this before I tried it out, but a few things cropped up that were causing issues.

1. No option/alternative way to use system libraries. Note that literally all used libraries (except Glslang) can be found using `find_package()`, although FindVulkan requires minimum Cmake v3.7
2. [These lines](https://github.com/Equilibrium-Games/Acid/blob/f60d625ad33badde6e7fa55113030efb217731bb/Sources/CMakeLists.txt#L57-L58) cause install to prefix all header install locations with junk. Example: `/usr/include/Acid/home/sum01/dev/Acid/Sources/Acid.hpp` when it should be `/usr/include/Acid/Acid.hpp`

Some Cmake notes:

- I recommend `include(GNUInstallDirs)` for sensible, user-overridable installation default locations instead of [all of this](https://github.com/Equilibrium-Games/Acid/blob/f60d625ad33badde6e7fa55113030efb217731bb/CMakeLists.txt#L94-L108)
- All references to `LIB_TYPE` in the Cmake files can be removed, even from `add_library()`. This is because `add_library()` already changes to STATIC/SHARED based on what `BUILD_SHARED_LIBS` is set to.
- `BUILD_TESTING` is a more common/standard name for a Cmake testing flag (it's defined in [CTest](https://cmake.org/cmake/help/latest/module/CTest.html?highlight=ctest))
- I'm pretty sure [all of this](https://github.com/Equilibrium-Games/Acid/blob/f60d625ad33badde6e7fa55113030efb217731bb/CMakeLists.txt#L20-L29) will only work for single-configuration systems, such as Make & Ninja. MSVC (and others?) use multi-configuration, which ignores `CMAKE_BUILD_TYPE`. Note you can check for `#ifdef NDEBUG` as [Cmake defines it automatically](https://stackoverflow.com/a/8594122)
 on release builds, at least when I've tested it.
- You can do project versioning in the `project()` call, which automatically sets all the various `ACID_XXX_VERSION` and `ACID_VERSION` vars. Example: `project(Acid VERSION 0.10.0 LANGUAGES C CXX)` (specifying the used languages is also nice).
- Having `ACID_INSTALL` as an option is pointless. If someone doesn't want to install they can just not use the `--target install` flag when calling cmake.
- The threads library from [FindThreads](https://cmake.org/cmake/help/latest/module/FindThreads.html?highlight=findthreads) is never actually linked against your lib. Either link against `${CMAKE_THREAD_LIBS_INIT}` or require minimum Cmake v3.1 and link against the target `Threads::Threads`
- Using file globbing makes Cmake re-run everything every time, as it can't track changes. While annoying, it is recommended to put each file name in the CMakeLists.txt. I recommend using [target_sources](https://cmake.org/cmake/help/latest/command/target_sources.html?highlight=target_sources) with the proper private/public settings for headers & sources.

Hopefully I'm not coming off as annoying, just trying to be helpful.

**Comment by mattparks** [comment]
I totally agree with everything you have said, I will start implementing all points listed. How should the install process run, all libraries using cmake use a different process. Thanks for the help!

**Comment by sum01** [comment]
I'm assuming you mean how to install headers while maintaining their file structure?

If so, the following should work, and is the recommended process in the [documentation.](https://cmake.org/cmake/help/latest/command/install.html?highlight=install#directory)

This is an example for your `Sources/CMakeLists.txt`
```cmake
include(GNUInstallDirs)
install(TARGETS Acid
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
)
# The forward-slash is important, otherwise the dirname would prefix everything
# This WILL maintain file structure for any headers installed
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/"
    # PROJECT_NAME comes from project() and will be whatever it is, so "Acid"
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}"
    FILES_MATCHING
        PATTERN "*.h"
        PATTERN "*.hpp"
)
```

---

Another intersting feature to note is [export](https://cmake.org/cmake/help/latest/command/export.html?highlight=export) which lets other Cmake users easily `find_package(Acid 1.2.3 REQUIRED)` once the project is installed.

A working example is [Snappy (search for export)](https://github.com/google/snappy/blob/master/CMakeLists.txt) which I believe does it right.

**Comment by sum01** [comment]
I had some free time so I made some changes to get everything successfully building using system libs, and (hopefully) without messing up the local lib build process. I also went ahead and cleaned up the `add_definition`'s a bit for more fine-grained control.

Although I notice it installs tests (a bit odd), and `add_test` isn't used (which makes testing as easy as running `ctest`).

If you want, I could submit a PR with what I have at the moment, or I can try to get export working, and fiddle with the tests a bit.

**Comment by mattparks** [comment]
It would be awesome if you could submit a pull request with your changes. In my past few commits I have been trying to clean up cmake and dependencies, I was not uncertain about using ctest because all submodules I have called tests have acted as examples.

**Comment by sum01** [comment]
Would an `ACID_INSTALL_EXAMPLES` maybe be preferrable? They could still act as tests with the `add_test` command, but also be installed if people want them to.

And I'm supprised `GNUInstallDirs` doesn't work. What was the issue with it? I've had it work just fine from the command prompt with MSVC

**Comment by mattparks** [comment]
I used to have the tests directory named examples, I just preferred having that directory ordered after sources, `add_test` would probably work fine to represent those executables. I have now managed to get `GNUInstallDirs` working (required a full cmake rebuild). It is nice having files output to a Build folder, also .exes don't have access to the project dlls that would normally be output to `Build/Debug/Bin`.

**Comment by sum01** [comment]
I get the automated-ness of having to do nothing and have it spit it into a build dir, but the same can be achieved by passing those hard-coded lines with a `-D` when calling cmake. This avoids hard-coded stuff, and gives the person build more flexibility.

So you should be able to pass `cmake -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=Build/Debug/Bin ..` for the same effect.

Me personally, I have an alias `cmakebuild` that will do everything: make a build dir, move into it, build debug with tests, compile with all threads, and run tests.

---

I'll clean it up a little and then push my repo to a fork.
