### ISSUE TITLE
Segfaults in some tests

### ISSUE THREAD

**Issue by sum01** [EQMG/Acid#29]
Mildy modified TestGUI's Main.cpp to point to the `assets` folder (instead of `Resources/Engine`) I copied into my test project.

Running it (with gdb) results in:
```
Reading symbols from acid_test...done.
(gdb) run
Starting program: acid_test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffee487700 (LWP 4638)]
Selected Physical Device: 'AMD RADV RAVEN (LLVM 7.0.0)', 5597
[New Thread 0x7fffed88f700 (LWP 4639)]
[Detaching after fork from child process 4640]
[Thread 0x7fffed88f700 (LWP 4639) exited]
[New Thread 0x7fffed88f700 (LWP 4641)]
[New Thread 0x7fffed88f700 (LWP 4642)]
[Thread 0x7fffed88f700 (LWP 4641) exited]
[New Thread 0x7fffe7ddf700 (LWP 4643)]
[New Thread 0x7fffe73b7700 (LWP 4644)]

Thread 1 "acid_test" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ef41c4 in acid::ShaderProgram::LoadUniform(glslang::TProgram const&, unsigned int const&, int const&) () from /usr/lib/libAcid.so
(gdb) n
Single stepping until exit from function _ZN4acid13ShaderProgram11LoadUniformERKN7glslang8TProgramERKjRKi,
which has no line number information.
[Thread 0x7fffe73b7700 (LWP 4644) exited]
[Thread 0x7fffe7ddf700 (LWP 4643) exited]
[Thread 0x7fffed88f700 (LWP 4642) exited]
[Thread 0x7ffff4f1f740 (LWP 4634) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb) quit
```

I think it has something to do with resource loading, although I'm not sure what specifically just yet. I'm assuming anyways, as "Maths" and "Network" tests pass, while the rest segfault.

Test results (unmodified from source), for example:
```
    Start 1: GUI
1/6 Test #1: GUI ..............................***Exception: SegFault  0.65 sec
    Start 2: Maths
2/6 Test #2: Maths ............................   Passed    0.02 sec
    Start 3: Network
3/6 Test #3: Network ..........................   Passed    0.02 sec
    Start 4: PBR
4/6 Test #4: PBR ..............................***Exception: SegFault  0.67 sec
    Start 5: Physics
5/6 Test #5: Physics ..........................***Exception: SegFault  0.68 sec
    Start 6: Voxel
6/6 Test #6: Voxel ............................***Exception: SegFault  0.64 sec
```

Seems this is very similar to #12 

---

Also, how would you feel about installing the Resources folder when Cmake installs everything? Since it's used a bit throughout the code, I feel it might make sense to distribute.

**Comment by mattparks** [comment]
On Windows when SPIRV is built with `ENABLE_NV_EXTENSIONS=ON` I am getting a segfault at the exact same point, this needs to be investigated further but is a cross platform issue. Resources would be distributed in a few `data.X.zip` files in the future, for now having Resources installed with cmake would be fine. Also on Ubuntu I am having issues compiling, it appears to be finding libSPIRV, but when a Tests is linked it cannot find it at all.

**Comment by mattparks** [comment]
I have been trying out a lot of compile options with glslang and what I found is that AMD and NVIDIA options were causing issues in the reflections generated in Acid (some combinations just outright causing segfaults). I was able to find some workarounds with bitter-sweat results, I posted my findings here: https://github.com/KhronosGroup/glslang/issues/1617

**Comment by warrantyvoids** [comment]
Which version of the SPIRV-libraries are used here?

**Comment by manuel5975p** [comment]
On my system, Tutorial 1-6 instantly segfault in the constructor of engine.
I run them on Ubuntu 20.04, compiled with g++ 9.

**Comment by mattparks** [comment]
The segfaults seen in the Test applications are due to glslang, the temporary fix was to just build it as a part of the Acid project to avoid the problem. Tutorials 1-6 have an unrelated issue causing them to not run correctly on all platforms, this will be fixed with a batch of graphics objects destruction fixes.

This ties into testing Acid on more platforms to catch dependencies not working as expected, driver issues, and use of a compiler sometimes resulting in runtime errors.
