### ISSUE TITLE
compilation error linux mint 19.2 g++ 7.4.0

### ISSUE THREAD

**Issue by nattydread69** [EQMG/Acid#78]
/home/natty/code/Acid/Sources/StdAfx.hpp:11:10: fatal error: filesystem: 
No such file or directory  

> #include < filesystem >

I can bypass it by with 
 #include <experimental/filesystem>

then other errors appear elsewhere.
Any advice?

**Comment by mattparks** [comment]
You will need to upgrade to g++ 8 or above for std::filesystem. I think this question may help you get that installed: https://askubuntu.com/a/1028656
I personally use gcc9 and g++9, or clang8.

**Comment by Spirrwell** [comment]
I haven't actually tried compiling Acid on Linux, but a small note, I have run into weird crashing issues with GCC 8 when using C++17's filesystem library, even when just using std::filesystem::path.

So I would definitely recommend GCC 9 or higher or of course clang.

**Comment by nattydread69** [comment]
I'll try gcc9. Thanks for the advice.
