### ISSUE TITLE
Could not find registered component: "skyboxCycle"

### ISSUE THREAD

**Issue by engineer1109** [EQMG/Acid#81]
When starting ./Editor,

[Host] Updating plugin
[Guest] Operation load: 1
[Game] Constructor
Working Directory: "/media/wjl/0B8803760B880376/github/2/Acid/build/bin"
Failed to mount path Resources/Engine, not found
Could not find registered component: "skyboxCycle"

The screen is black, and nothing exists. Is missing sth?

System: ubuntu18.04  driver: Nvidia 435  Vulkan 1.121

**Comment by mattparks** [comment]
It appears this is a bug only in the Editor introduced after https://github.com/EQMG/Acid/commit/7ac899216031792531028f29d1d6e2ab7f30a151, do the other test applications run fine on your system?

**Comment by engineer1109** [comment]
@mattparks  No.
The ./TestGUI and ./TestFont have mistakes of text location. And texts are overlapping.
The ./TestPhysics always meets segmentation fault.
And all programs Crashes on Resizing Windows due to the swapchain bugs, and also crashes xwindow system as well.

**Comment by mattparks** [comment]
I'm not aware of any known Linux bugs with TestPhysics on master, could you share what CPU and GPU you are running? If you could run a debug tool like gdb or debug in a editor like Clion or Visual Studio Code to see where this is exactly crashing.

**Comment by engineer1109** [comment]
@mattparks 
Thread 1 "TestPhysics" received signal SIGSEGV, Segmentation fault.
0x00007ffff76ab878 in std::__shared_ptr<acid::GizmoType, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<acid::GizmoType, (__gnu_cxx::_Lock_policy)2> const&) () from /media/wjl/0B8803760B880376/github/2/Acid/build/lib/libAcid.so

It seems happening on anything include camera droppes out of the world

**Comment by engineer1109** [comment]
@I am sure that throwing balls falling into the abyss will cause crash

**Comment by mattparks** [comment]
The log message `Could not find registered component: "skyboxCycle"` can be ignored, it is a prefab component not used in Physics or PBR. Bullet does not like deleting colliders when compiled on GNU, that is what caused the crash when the balls hit the despawn height (I disabled that event for now in 9586130884a72bc156842d350276d6807edd55e1). I'll investigate the editor crash a bit later today, it's probably a issue from my renderer refactor a few days back in 623c63dcaf7b3af4464b883e18ad5da989090205.

**Comment by engineer1109** [comment]
@mattparks  The TestPhysics no crash now.
