### ISSUE TITLE
ucrtbase dll crashing on certain tests

### ISSUE THREAD

**Issue by LukePrzyb** [EQMG/Acid#86]
Running TestPhysics provides me with this error before code even begins executing:

`Unhandled exception at 0x00007FFD4D8EE91E (ucrtbase.dll) in TestPhysics.exe: Fatal program exit requested`

The console provides some more insight, with errors such as:

`Type mismatch on descriptor slot 0.0 (expected `VK_DESCRIPTOR_TYPE_STORAGE_IMAGE`) but descriptor of type VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`
`THREADING ERROR : object of type VkQueue is simultaneously used in thread 0x2214 and thread 0x3ed0`

My step-by-step build so far can be found [Here](https://github.com/LukePrzyb/Acid/blob/master/README.md) under the Compiling category.

**Comment by LukePrzyb** [comment]
Currently re-going through the CMake to ensure that there wasnt something missed with additional components

**Comment by LukePrzyb** [comment]
Curses.. I seem to have caused a CMake error somehow...

```
Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error		CMake Error in Sources/CMakeLists.txt:
  Target "Acid" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "C:/.../Desktop/Acid/Sources"

  which is prefixed in the source directory.					
```
Will revisit this later.

**Comment by mattparks** [comment]
I'm getting this runtime error with vcpkg's glslang version, the vcpkg builds from commit: https://github.com/KhronosGroup/glslang/commit/f88e5824d2cfca5edc58c7c2101ec9a4ec36afac
Acid builds glslang if it was not found on the system, doing this works fine (I would set a glslang min version for find_package but as far as I can tell they don't distribute with versions 🤦‍♂).

I was getting that `Target "Acid" INTERFACE_INCLUDE_DIRECTORIES property contains path` error initially, after regenerating my project I can build fine. 


Notes for Acid dependencies that can be found in vcpckg:
 - `glfw3:x64-windows` works great on my machine!
 - `freetype:x64-windows` this error is throw when compiling: `error : build.ninja:3162: bad $-escape (literal $ must be written as $$)`
 - `gtest:x64-windows` for some reason includes cannot be found when compiling, or CMake errors like: `Target "UnitTests" links to target "GTest::gtest" but the target was not found`

**Comment by LukePrzyb** [comment]
>`glfw3:x64-windows` works great on my machine

I had a feeling this was the case. I had glfw on hand when I was playing around with that, and vulkan. I will update once I figure out my cmake issue, which still hasn't gone away even after I deleted my cache. 
I did, however, automatically get glfw3 from vcpkg working.

**Comment by mattparks** [comment]
I was able to replicate your most recent error, commenting out this line fixed my build:
https://github.com/EQMG/Acid/blob/d7e83f06f2a474c3ba376c9d4dda69947afcac28/Sources/CMakeLists.txt#L82

I'm also attempting to create a vcpkg port for Acid, a few minor CMake changes will be required for it to work well. 
I'm still recommending building Acid in projects as a submodule.

**Comment by LukePrzyb** [comment]
I see.. this did indeed fix it for me.

If it isn't intended to be built as a primary target, that is most likely confusing the build. It would explain why I was being misled by explanations online.

With that out of the way, I will start looking into the cmake building of PhysicsTest.exe

**Comment by LukePrzyb** [comment]
CMake isn't giving any hints on underlying issues, mostly conversion warnings and some notes.

The debug console is spitting out some vulkan complaints. I suspect these are based on newer vulkan versions.

Some sample complaints:
```
Vertex attribute at location 2 not consumed by vertex shader
Attempt to free VkCommandBuffer 0x1eee5e33350[] which is in use. The Vulkan spec states: All elements of pCommandBuffers must not be in the pending state
vkCreateGraphicsPipelines(): VkRenderPass 0xc0b7f20000000108[] subpass 0 has colorAttachmentCount of 4 which doesn't match the pColorBlendState->attachmentCount of 1. The Vulkan spec states: If rasterization is not disabled and the subpass uses color attachments, the attachmentCount member of pColorBlendState must be equal to the colorAttachmentCount used to create subpass
```

I will install 1.0.X of vulkan and see what I get from there, else i'll start looking into my CMakeList.json again.

**Comment by LukePrzyb** [comment]
The good news is - it looks as if the last version of vulkan 1.0 (1.0.68) solves ALL those problems. Nice.

I am still getting the same fatal error, but I did notice this:
```
Failed to mount path Resources/Engine, not found
```

**Comment by mattparks** [comment]
I used a newer version of glslang to develop shader parsing in Acid, vcpkg uses a older release. I opened a PR with vcpkg for a release version increase: https://github.com/microsoft/vcpkg/pull/8990

**Comment by LukePrzyb** [comment]
Apologies. Trying to re-run TestPhysics caused my entire GPU to brick the desktop screen, and life duties called.

Stacktrace shows it coming from Engine Run, then chain reacting into drawing imagecube, and going then into the depths of msvc. [Screenshot](https://imgur.com/yjRBgim)

**Comment by mattparks** [comment]
Are Editor, TestPhysics and TestPBR the only executables that crash? If you comment out the Enqueue around these lambdas, do those tests still crash?
https://github.com/EQMG/Acid/blob/944a6247f2de0014213bcf808c4f6500e18f21b9/Sources/Post/Deferred/SubrenderDeferred.cpp#L139
https://github.com/EQMG/Acid/blob/944a6247f2de0014213bcf808c4f6500e18f21b9/Sources/Post/Deferred/SubrenderDeferred.cpp#L174
https://github.com/EQMG/Acid/blob/944a6247f2de0014213bcf808c4f6500e18f21b9/Sources/Post/Deferred/SubrenderDeferred.cpp#L241

**Comment by LukePrzyb** [comment]
I'm getting an LNK2019 error on `Shader.cpp` in the CMakeSources list, saying there's an unresolved external symbol from glslang. I changed HLSL_LIBRARY, GLSLANG_LIBRARY / INCLUDE, and SPIRV_LIBRARY / INCLUDE.

I switched out to the vcpkg version and try your change, and there was no difference for TestPhysics. 
[Here is Editor's stacktrace while I was at it](https://i.imgur.com/4KQwxRX.png)

**Comment by LukePrzyb** [comment]
Working now. Some minor hiccups on SPIV but i'll re-visit this tomorrow.

**Comment by LukePrzyb** [comment]
Ignoring those enqueue's in ACID_DEBUG works with the build, but it's causing exceptions to get thrown on cleanup. Perhaps this is because of how my build is set up? Since it is a `x64-RelWithDebInfo` so it's a hybrid release / debug build. Might get better results just building as a release strictly?

Here's the [screenshot](https://i.imgur.com/8p6pR8g.png)

 I'll open up a few more issues separately to see if they can be pinpointed.

**Comment by LukePrzyb** [comment]
In addition: running a newer glslang with commented out enqueues also works, but has more visual issues. Also: There seems to be a vulkan crash where things arent getting cleaned up properly in `vkFreeCommandBuffers` from `CommandBuffer.cpp` line 26. Perhaps the first step would be to resolve that issue, and then figure out what's causing crashes on exit due to other issues that aren't coming from vulkan.

**Comment by mattparks** [comment]
Almost all cleanup issues are my fault, I'm deleting Vulkan objects in the wrong order a large amount of the time. I had these methods correct before a fairly major Vulkan overhaul, they have not been my top priority. 
This should only cause issues when closing the application, not when deleting entities or destroying command pools/buffers.

**Comment by Luke-P-SF** [comment]
No problem - I was more concerned with my LNK2019 issue, but I couldn't recreate it (I should have been more rigorous on what I was changing and testing)

I think staying on Vulkan 1.0.X and ensuring cleanup stability, THEN upgrading to Vulkan 1.1.X, is the ideal solution.

I'll look into merging my documentation later today hopefully, and work on other pressing issues.
